"""empty message

Revision ID: 9b53a6374401
Revises: ec07f067b572
Create Date: 2019-11-04 12:49:36.086719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b53a6374401'
down_revision = 'ec07f067b572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('soft',
    sa.Column('soft_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=30), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('soft_id')
    )
    op.add_column('repo', sa.Column('soft_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'repo', 'soft', ['soft_id'], ['soft_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repo', type_='foreignkey')
    op.drop_column('repo', 'soft_id')
    op.drop_table('soft')
    # ### end Alembic commands ###
