"""empty message

Revision ID: ec07f067b572
Revises: 9de1f0a7181a
Create Date: 2019-11-03 23:10:50.626634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec07f067b572'
down_revision = '9de1f0a7181a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('language', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'language')
    # ### end Alembic commands ###
